config/routes.rb
Rails.application.routes.draw do

    namespace :admin do
    resources:genres,only:[:edit,:create,:index,:update]
    resources:items,only:[:new,:index,:create,:show,:edit,:update]
    resources:customers,only:[:index,:show,:edit,:update]
    resources:orders,only:[:show,:update] do
    resources :order_details, only: [:update]
    end
  end
  get 'admin'=>"admin/homes#top"


   scope module: :public do
    resources :addresses,only:[:edit,:create,:index,:update,:destroy]
    resources :items,only:[:index,:show]
    resources :cart_items,only:[:index,:update,:create,:destroy]
    delete 'cart_items'=>"cart_items#destroy_all"
    post "orders/confirm" => "orders#confirm"
    get "orders/complete" => "orders#complete"
    resources :orders,only:[:index,:new,:create,:show]
  end


 #顧客の会員
 get 'customers/my_page'=>"public/customers#show"
 get 'customers/edit'=>"public/customers#edit"
 patch "customers" => "public/customers#update"
 get 'customers/unsubscribe'=>"public/customers#unsubscribe"
 patch "customers/withdrawal" => "public/customers#withdrawal"

  root to: 'public/homes#top'
  get 'about'=>"public/homes#about"

 devise_for :admin,skip: [:passwords],  controllers: {
  sessions: "admin/sessions",
  registrations: "admin/registrations"
 }

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}


 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items,dependent: :destroy
  has_many:order_details,dependent: :destroy

 attachment :image

 validates :name,presence: true
 validates :introduction,presence: true
 validates :price,presence: true,numericality: true
 validates :image,presence: true


 def with_tax_price
    (price * 1.1).floor
 end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new

  end

  def create
    @item=Item.new(item_params)
    if @item.save
    redirect_to admin_item_path(@item.id)
    flash[:notice] = "商品追加しました."
    else
    render :new
    end
  end


  def show
    @item=Item.find(params[:id])
  end

  def edit
     @item=Item.find(params[:id])
  end

  def update
    @item=Item.find(params[:id])
    if @item.update(item_params)
    redirect_to admin_item_path(@item.id)
    flash[:notice] = "商品内容更新しました."
    else
    render :edit
    end
  end
    private

  def item_params
    params.require(:item).permit(:name,:introduction,:price,:is_active,:image,:genre_id)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class='container'>

  <div class="py-5 body heading">
    <span class="col-md-3 bg-light" style="font-size : 30pt">商品編集</span>
  </div>

    <% if  @item.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <div id="error_explanation">
          <ul>
            <% @item.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
    
  <%= form_with model:@item,url:admin_item_path(@item.id) do |f| %>

    <form class="form-horizontal">
    <div class="form-group">
      <%= f.label :image,"商品画像" ,class:"col-lg-2 col-form-label font-weight-bold" %>
      <%= f.attachment_field :image,placeholder:"ファイルを選択",accept:"image/*" %>
    </div>

    <div class="form-group">
      <%= f.label :name,"商品名" ,class:"col-lg-2 col-form-label font-weight-bold" %>
      <%= f.text_field :name ,placeholder:"商品名",class: "col-lg-5"  %>
    </div>

    <div class="form-group">
      <%= f.label :introduction,"商品説明" ,class:"col-lg-2 col-form-label font-weight-bold" %>
      <%= f.text_area :introduction,rows:10,class:"col-lg-5",placeholder:"ここに説明を記述します。" %>
    </div>

    <div class="form-group">
      <%= f.label :genre_id,"ジャンル" ,class:"col-lg-2 font-weight-bold" %>
      <%= f.collection_select :genre_id,Genre.all,:id,:name, include_blank: "--選択して下さい--　　　　　　　　　　　　　　　　　　　"  %>
    </div>

    <div class="form-group">
      <%= f.label :price,"税抜価格" ,class:"col-lg-2 col-form-label font-weight-bold" %>
      <%= f.text_field :price,class:"col-lg-5" ,placeholder:"1000" %>円
    </div>

    <div class="form-group">
      <%= f.label :is_active,"販売ステータス" ,class:"col-lg-2 col-form-label font-weight-bold" %>
      <%= f.radio_button :is_active, true, checked: true %>&thinsp;販売中
      <span>&emsp;</span>
      <%= f.radio_button :is_active, false %>&thinsp;販売停止中
    </div>

    <div class="form-group">
      <div class="col-lg-7 text-center">
      <div class="actions">
        <%= f.submit "変更を保存",class:"col-md-3 btn btn-success btn-lg " %>
      </div>
      </div>
    </div>
  <% end %>
 </div>


</div>

app/views/admin/items/index.html.erb
<div class='container'>

  <div class="row py-5 body heading">
     <div class="col-8">
      <span class="col-md-3 bg-light" style="font-size : 30pt">商品一覧</span>
     </div>
     <div class="col-4">
     <%= link_to "＋",new_admin_item_path ,class:"shadow-lg btn rounded-circle p-0 btn-light",style:"width:4rem;height:4rem;color:black;font-size : 30pt;"  %>
  </div>
    </div>

  <table class="table table-borderless">
    <thead style="border-top: 1px solid silver;">
      <tr>
        <th class="bg-light" >商品ID</th>
        <th class="bg-light" >商品名</th>
        <th class="bg-light" >税抜価格 </th>
        <th class="bg-light" >ジャンル</th>
        <th class="bg-light" >ステータス</th>
      </tr>
    </thead>
    <tbody style="border-bottom: 1px solid silver;">
    <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= link_to item.name,admin_item_path(item.id),:style =>"color:black; text-decoration: underline;" %></td>
        <td><%= item.price.to_s(:delimited) %></td>
        <td><%= item.genre.name %></td>
        <% if item.is_active==true %>
          <td class="font-weight-bold"><font color="green">販売中</td>
          <% else %>
          <td class="font-weight-bold"><font color="gray">販売停止中</td>
          <% end %>
          </tr>
        <% end %>
    </tbody>
  </table>

  <%= paginate @items %>

</div>

app/views/admin/items/new.html.erb
<div class='container'>

  <div class="py-5 body heading">
    <span class="col-md-3 bg-light" style="font-size : 30pt">商品新規登録</span>
  </div>

    <% if  @item.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <div id="error_explanation">
          <ul>
            <% @item.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
    
  <%= form_with model:@item,url:admin_items_path do |f| %>
  
    <form class="form-horizontal">
    <div class="form-group">
      <%= f.label :image,"商品画像" ,class:"col-lg-2 col-form-label font-weight-bold" %>
      <%= f.attachment_field :image,placeholder:"ファイルを選択",accept:"image/*" %>

    <div class="form-group">
      <%= f.label :name,"商品名" ,class:"col-lg-2 col-form-label font-weight-bold" %>
      <%= f.text_field :name ,placeholder:"商品名",class: "col-lg-5"  %>
    </div>

    <div class="form-group">
      <%= f.label :introduction,"商品説明" ,class:"col-lg-2 col-form-label font-weight-bold" %>
      <%= f.text_area :introduction,rows:10,class:"col-lg-5",placeholder:"ここに説明を記述します。" %>
    </div>

    <div class="form-group">
      <%= f.label :genre_id,"ジャンル" ,class:"col-lg-2 font-weight-bold" %>
      <%= f.collection_select :genre_id,Genre.all,:id,:name,class:"col-lg-12", include_blank: "--選択して下さい--　　　　　　　　　　　　　　　　　　　"  %>
    </div>

    <div class="form-group">
      <%= f.label :price,"税抜価格" ,class:"col-lg-2 col-form-label font-weight-bold" %>
      <%= f.text_field :price,class:"col-lg-5" ,placeholder:"1000" %>円
    </div>

    <div class="form-group">
      <%= f.label :is_active,"販売ステータス" ,class:"col-lg-2 col-form-label font-weight-bold" %>
      <%= f.radio_button :is_active, true, checked: true %>&thinsp;販売中
      <span>&emsp;</span>
      <%= f.radio_button :is_active, false %>&thinsp;販売停止中
    </div>

    <div class="form-group">
      <div class="col-lg-7 text-center">
      <div class="actions">
        <%= f.submit "新規登録",class:"col-md-3 btn btn-success btn-lg " %>
      </div>
      </div>
    </div>
  <% end %>
 </div>
 
</div>

app/views/admin/items/show.html.erb
<div class='container'>

  <div class="py-5 body heading">
    <span class="col-md-3 bg-light" style="font-size : 30pt">商品詳細</span>
  </div>


  <div class="row">
    <div class="col-lg-3">
     <%= attachment_image_tag @item, :image, format: 'jpeg',size:"300x200" %>
    </div>

  <div class="col-lg-8 offset-lg-1">
   <table style="table-layout:fixed;width:100%;">
    <tr>
      <td class="font-weight-bold col-sm-3">商品名</td>
      <td style="word-wrap:break-word;"><%= @item.name  %></td>
    </tr>
    <tr>
      <td class="font-weight-bold col-sm-3">商品説明</td>
      <td style="word-wrap:break-word;"><%= @item.introduction %></td>
    </tr>
    <tr>
      <td class="font-weight-bold col-sm-3">ジャンル</td>
      <td style="word-wrap:break-word;"><%= @item.genre.name  %></td>
    </tr>
    <tr>
      <td class="font-weight-bold col-sm-3">税込価格<br>(税抜価格)</br></td>
      <td style="word-wrap:break-word;"><%= (@item.price*1.1).floor.to_s(:delimited) %>(<%= (@item.price).floor.to_s(:delimited) %>)円</td>
    </tr>
    <tr>
      <td class="font-weight-bold col-sm-3">販売ステータス</td>
      <% if @item.is_active==true %>
      <td class="font-weight-bold"><font color="green">販売中</td>
      <% else %>
      <td class="font-weight-bold"><font color="gray">販売停止中</td>
      <% end %>
    </tr>
    <tr><td>&thinsp;</td></tr>
    <tr>
      <td colspan="2">
        <%= link_to "編集する",edit_admin_item_path(@item.id),class:"col-sm-3 offset-md-1 btn btn-success btn-lg " %>
      </td>
    </tr>
  </table>

  </div>
  </div>
</div>