config/routes.rb
Rails.application.routes.draw do

    namespace :admin do
    resources:genres,only:[:edit,:create,:index,:update]
    resources:items,only:[:new,:index,:create,:show,:edit,:update]
    resources:customers,only:[:index,:show,:edit,:update]
    resources:orders,only:[:show,:update] do
    resources :order_details, only: [:update]
    end
  end
  get 'admin'=>"admin/homes#top"


   scope module: :public do
    resources :addresses,only:[:edit,:create,:index,:update,:destroy]
    resources :items,only:[:index,:show]
    resources :cart_items,only:[:index,:update,:create,:destroy]
    delete 'cart_items'=>"cart_items#destroy_all"
    post "orders/confirm" => "orders#confirm"
    get "orders/complete" => "orders#complete"
    resources :orders,only:[:index,:new,:create,:show]
  end


 #顧客の会員
 get 'customers/my_page'=>"public/customers#show"
 get 'customers/edit'=>"public/customers#edit"
 patch "customers" => "public/customers#update"
 get 'customers/unsubscribe'=>"public/customers#unsubscribe"
 patch "customers/withdrawal" => "public/customers#withdrawal"

  root to: 'public/homes#top'
  get 'about'=>"public/homes#about"

 devise_for :admin,skip: [:passwords],  controllers: {
  sessions: "admin/sessions",
  registrations: "admin/registrations"
 }

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}


 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :addresses,dependent: :destroy
  has_many:cart_items,dependent: :destroy
  has_many:orders,dependent: :destroy
  has_many:order_details,dependent: :destroy
  
  
    validates :last_name, presence: true
    validates :first_name, presence: true
    validates :last_name_kana, presence: true
    validates :first_name_kana, presence: true
    validates :email, presence: true,uniqueness: true
    validates :first_name, presence: true    
    validates :postal_code, presence: true,numericality: true
    validates :address, presence: true
    validates :telephone_number, presence: true,numericality: true

def full_name
  last_name+first_name
end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer =Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
    flash[:notice] = "会員情報更新しました."
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:email,:postal_code,:address,:telephone_number,:is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class='container'>


  <div class="py-5 body heading">
    <span class="col-md-3 bg-light" style="font-size : 30pt"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</span>
  </div>


    <% if  @customer.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <div id="error_explanation">
          <ul>
            <% @customer.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>


  <%= form_with model:@customer,url:admin_customer_path(@customer.id) do |f| %>

    <div class="mx-5" >
      
      <div class="row mt-3">
        <div class="col-md-2">
          <span class="font-weight-bold">会員ID</span>
        </div>
        <div class="colo-md-10">
          <%= @customer.id %>
        </div>
      </div>

      <div class="row mt-3">
        <div class="col-md-2">
          <%= f.label :last_name,"氏名",class:"font-weight-bold" %>
        </div>
        <div class="colo-md-10">
          <%= f.text_field :last_name,class:"mb-1" %><span>&emsp;&emsp;</span><%= f.text_field :first_name %>
        </div>
      </div>

      <div class="row mt-3">
        <div class="col-md-2">
          <%= f.label :last_name_kana,"フリガナ",class:"font-weight-bold" %>
        </div>
        <div class="colo-md-10">
          <%= f.text_field :last_name_kana,class:"mb-1" %><span>&emsp;&emsp;</span><%= f.text_field :first_name_kana %>
        </div>
      </div>

      <div class="row mt-3">
        <div class="col-md-2">
          <%= f.label :postal_code,"郵便番号",class:"font-weight-bold"  %>
        </div>
        <div class="colo-md-10">
          <%= f.text_field :postal_code %>
        </div>
      </div>

      <div class="row mt-3">
        <div class="col-md-2">
          <%= f.label :address,"住所",class:"font-weight-bold"  %>
        </div>
        <div class="colo-md-10">
          <%= f.text_field :address,:size => "50*30" %>
        </div>
      </div>

      <div class="row mt-3">
        <div class="col-md-2">
          <%= f.label :name,"電話番号",class:"font-weight-bold"  %>
        </div>
        <div class="colo-md-10">
          <%= f.text_field :telephone_number %>
        </div>
      </div>

      <div class="row mt-3">
        <div class="col-md-2">
          <%= f.label :email,"メールアドレス",class:"font-weight-bold"  %>
        </div>
        <div class="colo-md-10">
          <%= f.text_field :email ,:size => "50*30" %>
        </div>
      </div>

      <div class="row mt-3">
        <div class="col-md-2">
          <%= f.label :is_deleted,"会員ステータス",class:"font-weight-bold"  %>
        </div>
        <div class="colo-md-10">
          <%= f.radio_button :is_deleted, false, checked: true %>&thinsp;有効<span>&emsp;</span><%= f.radio_button :is_deleted, true %>&thinsp;退会
        </div>
      </div>

      <div class="col-md-10 mt-3  text-center">
        <div class="col-md-10">
          <%= f.submit "変更を保存",class:"btn btn-lg btn-success" %>
      </div>
    </div>
    <% end %>
    
    </div>


</div>

app/views/admin/customers/index.html.erb
<div class='container'>


  <div class="py-5 body heading">
    <span class="col-md-3 bg-light" style="font-size : 30pt">会員一覧</span>
  </div>


<table class="table">
  <thead>
    <tr>
      <th class="bg-light">会員ID</th>
      <th class="bg-light">氏名</th>
      <th class="bg-light">メールアドレス </th>
      <th class="bg-light">ステータス</th>
    </tr>
  </thead>
  <tbody style="border-bottom: 1px solid silver;">
    <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.id %></td>
      <td><%= link_to "#{customer.last_name+customer.first_name}",admin_customer_path(customer.id),:style =>"color:black; text-decoration: underline;" %></td>
      <td><%= customer.email %></td>
      <% if customer.is_deleted==false %>
       <td class="font-weight-bold" ><font color="green">有効</td>
       <% else %>
       <td class="font-weight-bold"><font color="gray">退会</td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>


<%= paginate @customers %>


</div>

app/views/admin/customers/show.html.erb
<div class='container'>

  <div class="py-5 body heading">
    <span class="col-md-3 bg-light" style="font-size : 30pt"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</span>
  </div>

  <table style="table-layout:fixed;width:100%;" >
     <tr height="40">
      <th class="col-md-2">会員ID</th>
      <td class="col-md-10"><%= @customer.id %></td>
     </tr>
     <tr height="40">
      <th class="col-md-2">氏名</th>
      <td class="col-md-10" style="word-wrap:break-word;"><%= @customer.last_name %>&emsp;<%= @customer.first_name %></td>
     </tr>
     <tr height="40">
      <th class="col-md-2">フリガナ</th>
      <td class="col-md-10" style="word-wrap:break-word;"><%= @customer.last_name_kana %>&emsp;<%= @customer.first_name_kana %></td>
     </tr>
     <tr height="40">
      <th class="col-md-2">郵便番号</th>
      <td class="col-md-10"><%= @customer.postal_code %></td>
     </tr>
     <tr height="40">
      <th class="col-md-2">住所</th>
      <td class="col-md-10" style="word-wrap:break-word;"><%= @customer.address %></td>
     </tr>
     <tr height="40">
      <th class="col-md-2">電話番号</th>
      <td class="col-md-10"><%= @customer.telephone_number %></td>
     </tr>
     <tr height="40">
      <th class="col-md-2">メールアドレス</th>
      <td class="col-md-10"><%= @customer.email %></td>
     </tr>
     <tr height="40">
      <th class="col-sm-2">会員ステータス</th>
      <% if @customer.is_deleted==false %>
      <td class="col-sm-10 font-weight-bold"><font color="green">有効</td>
      <% else %>
      <td class="col-md-10 font-weight-bold"><font color="gray">退会</td>
      <% end %>
     </tr>
     <tr height="40">
      <th class="col-sm-3"></th>
      <td class="col-sm-9"><%= link_to "編集する",edit_admin_customer_path(@customer.id),class:"btn btn-lg btn-success " %>&emsp;<%= link_to "注文履歴一覧を見る",admin_path,class:"btn btn-lg btn-primary " %></td>
     </tr>
  </table>





</div>