config/routes.rb
Rails.application.routes.draw do

    namespace :admin do
    resources:genres,only:[:edit,:create,:index,:update]
    resources:items,only:[:new,:index,:create,:show,:edit,:update]
    resources:customers,only:[:index,:show,:edit,:update]
    resources:orders,only:[:show,:update] do
    resources :order_details, only: [:update]
    end
  end
  get 'admin'=>"admin/homes#top"


   scope module: :public do
    resources :addresses,only:[:edit,:create,:index,:update,:destroy]
    resources :items,only:[:index,:show]
    resources :cart_items,only:[:index,:update,:create,:destroy]
    delete 'cart_items'=>"cart_items#destroy_all"
    post "orders/confirm" => "orders#confirm"
    get "orders/complete" => "orders#complete"
    resources :orders,only:[:index,:new,:create,:show]
  end


 #顧客の会員
 get 'customers/my_page'=>"public/customers#show"
 get 'customers/edit'=>"public/customers#edit"
 patch "customers" => "public/customers#update"
 get 'customers/unsubscribe'=>"public/customers#unsubscribe"
 patch "customers/withdrawal" => "public/customers#withdrawal"

  root to: 'public/homes#top'
  get 'about'=>"public/homes#about"

 devise_for :admin,skip: [:passwords],  controllers: {
  sessions: "admin/sessions",
  registrations: "admin/registrations"
 }

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}


 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    before_action :authenticate_admin!
  def top
    @orders=Order.order("created_at DESC").page(params[:page]).per(11)
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<div class='container'>

  <div class="py-5 body heading ">
    <div class="font-weight-bold">
    <span class="col-md-3 bg-light" style="font-size : 30pt">注文履歴一覧</span>
    </div>
  </div>

  <table class="table">
    <thead class="bg-light">
      <th>購入日時</th>
      <th>購入者</th>
      <th>注文個数</th>
      <th>注文ステータス</th>
      <th>製作ステータス</th>
    </thead>
    <tbody style="border-bottom: 1px solid silver;">
      <% @orders.each do |order| %>
      <% amount=order.order_details.sum(:amount)%>
      <tr>
        <td class="align-middle"><%= link_to order.created_at.strftime('%Y/%m/%d %X'),admin_order_path(order.id),:style =>"color:black; text-decoration: underline;" %></td>
        <td class="align-middle"><%= order.customer.last_name %><%= order.customer.first_name %></td>
        <td class="align-middle"><%= amount %></td>
        <td class="align-middle"><%= order.order_status_i18n %></td>
        <td>
          <% order.order_details.each do |order_detail| %>
            <%= order_detail.item.name %>
            <%= order_detail.making_status_i18n %></br>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

   <%= paginate @orders %>

 </div>