config/routes.rb
Rails.application.routes.draw do

    namespace :admin do
    resources:genres,only:[:edit,:create,:index,:update]
    resources:items,only:[:new,:index,:create,:show,:edit,:update]
    resources:customers,only:[:index,:show,:edit,:update]
    resources:orders,only:[:show,:update] do
    resources :order_details, only: [:update]
    end
  end
  get 'admin'=>"admin/homes#top"


   scope module: :public do
    resources :addresses,only:[:edit,:create,:index,:update,:destroy]
    resources :items,only:[:index,:show]
    resources :cart_items,only:[:index,:update,:create,:destroy]
    delete 'cart_items'=>"cart_items#destroy_all"
    post "orders/confirm" => "orders#confirm"
    get "orders/complete" => "orders#complete"
    resources :orders,only:[:index,:new,:create,:show]
  end


 #顧客の会員
 get 'customers/my_page'=>"public/customers#show"
 get 'customers/edit'=>"public/customers#edit"
 patch "customers" => "public/customers#update"
 get 'customers/unsubscribe'=>"public/customers#unsubscribe"
 patch "customers/withdrawal" => "public/customers#withdrawal"

  root to: 'public/homes#top'
  get 'about'=>"public/homes#about"

 devise_for :admin,skip: [:passwords],  controllers: {
  sessions: "admin/sessions",
  registrations: "admin/registrations"
 }

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}


 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to:customer

    validates :postal_code, presence: true,numericality: true
    validates :address, presence: true
    validates :name, presence: true

  def address_display
     '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  validates :amount, numericality: {less_than_or_equal_to: 100}

  def subtotal
    item.with_tax_price * amount
  end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :addresses,dependent: :destroy
  has_many:cart_items,dependent: :destroy
  has_many:orders,dependent: :destroy
  has_many:order_details,dependent: :destroy
  
  
    validates :last_name, presence: true
    validates :first_name, presence: true
    validates :last_name_kana, presence: true
    validates :first_name_kana, presence: true
    validates :email, presence: true,uniqueness: true
    validates :first_name, presence: true    
    validates :postal_code, presence: true,numericality: true
    validates :address, presence: true
    validates :telephone_number, presence: true,numericality: true

def full_name
  last_name+first_name
end
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many:items,dependent: :destroy
  
  validates :name,presence: true,uniqueness: true,length: {in: 2..20}
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items,dependent: :destroy
  has_many:order_details,dependent: :destroy

 attachment :image

 validates :name,presence: true
 validates :introduction,presence: true
 validates :price,presence: true,numericality: true
 validates :image,presence: true


 def with_tax_price
    (price * 1.1).floor
 end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many:order_details,dependent: :destroy

    validates :postal_code, presence: true,numericality: true
    validates :address, presence: true
    validates :name, presence: true

    def delivery_address
     '〒' + postal_code + ' ' + address
    end




  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: {waiting_payment: 0, confirmation_payment: 1, in_production: 2, preparing_shipping: 3, shipped: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: {cannotbe_manufactured: 0, waiting_production: 1, in_production: 2, production_completed: 3}

   def order_with_tax_price
    (price* 1.1).floor
   end
   
   def order_subtotal
    order_with_tax_price*amount
   end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  
  def create
    @genres=Genre.all
    @genre=Genre.new(genre_params)
    if @genre.save
    redirect_to admin_genres_path
    flash[:notice] = "ジャンル追加しました."
    else
    render :index
    end
  end  
  
  def index
    @genres = Genre.all
    @genre =Genre.new
  end

  def edit
    @genre=Genre.find(params[:id])
  end
  
  def update
    @genre=Genre.find(params[:id])
    if @genre.update(genre_params)
    redirect_to admin_genres_path
    flash[:notice] = "ジャンル更新しました."
    else
    render :edit
    end
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    before_action :authenticate_admin!
  def top
    @orders=Order.order("created_at DESC").page(params[:page]).per(11)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new

  end

  def create
    @item=Item.new(item_params)
    if @item.save
    redirect_to admin_item_path(@item.id)
    flash[:notice] = "商品追加しました."
    else
    render :new
    end
  end


  def show
    @item=Item.find(params[:id])
  end

  def edit
     @item=Item.find(params[:id])
  end

  def update
    @item=Item.find(params[:id])
    if @item.update(item_params)
    redirect_to admin_item_path(@item.id)
    flash[:notice] = "商品内容更新しました."
    else
    render :edit
    end
  end
    private

  def item_params
    params.require(:item).permit(:name,:introduction,:price,:is_active,:image,:genre_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when Customer
      root_path
    end

  end




  def after_sign_out_path_for(resource)
    case resource
    when :admin   # ログアウト時はシンボルが返ってくる
      new_admin_session_path
    when :customer  # ログアウト時はシンボルが返ってくる
      root_path
    end
  end

  protected

  def devise_parameter_sanitizer
    if resource_class == Customer
      Public::CustomerParameterSanitizer.new(Customer, :customer, params)
    else
      super # Use the default one
    end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag 'cake.png',size: "60x60" %></a>
            <% if customer_signed_in? %>
              <p class="text-right">ようこそ、<%= current_customer.last_name %>さん！</p>
            <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
              <div class="text-right pb-5">
                <li class="btn btn-light btn-lg" >
                  <%= link_to admin_items_path,:style =>"color:black;" do %>
                  商品一覧
                  <% end %>
                </li>
                <span>&emsp;</span>
                <li class="btn btn-light btn-lg" >
                  <%= link_to admin_customers_path,:style =>"color:black;" do %>
                  会員一覧
                  <% end %>
                </li>
                <span>&emsp;</span>
                <li class="btn btn-light btn-lg" >
                  <%= link_to admin_path,:style =>"color:black;" do %>
                  注文履歴一覧
                  <% end %>
                </li>
                <span>&emsp;</span>
                <li class="btn btn-light btn-lg" >
                  <%= link_to admin_genres_path,:style =>"color:black;" do %>
                  ジャンル一覧
                  <% end %>
                </li>
                <span>&emsp;</span>
                <li class="btn btn-light btn-lg" >
                  <%= link_to destroy_admin_session_path,:style =>"color:black;",method: :delete do %>
                  ログアウト
                  <% end %>
                </li>
              </div>
            <% elsif customer_signed_in? %>
              <div class="text-right pb-5">
                <li class="btn btn-light btn-lg" >
                  <%= link_to customers_my_page_path,:style =>"color:black;" do %>
                  マイページ
                  <% end %>
                </li>
                <span>&emsp;</span>
                <li class="btn btn-light btn-lg" >
                  <%= link_to items_path,:style =>"color:black;" do %>
                  商品一覧
                  <% end %>
                </li>
                <span>&emsp;</span>
                <li class="btn btn-light btn-lg" >
                  <%= link_to cart_items_path,:style =>"color:black;" do %>
                  カート
                  <% end %>
                </li>
                <span>&emsp;</span>
                <li class="btn btn-light btn-lg" >
                  <%= link_to destroy_customer_session_path,:style =>"color:black;",method: :delete do %>
                  ログアウト
                  <% end %>
                </li>
              </div>
            <% else %>
              <div class="text-right pb-5">
                <li class="btn btn-light btn-lg" >
                  <%= link_to about_path,:style =>"color:black;" do %>
                  About
                  <% end %>
                </li>
                <span>&emsp;</span>
                <li class="btn btn-light btn-lg" >
                  <%= link_to items_path,:style =>"color:black;" do %>
                  商品一覧
                  <% end %>
                </li>
                <span>&emsp;</span>
                <li class="btn btn-light btn-lg" >
                  <%= link_to new_customer_registration_path,:style =>"color:black;" do %>
                  新規登録
                  <% end %>
                </li>
                <span>&emsp;</span>
                <li class="btn btn-light btn-lg" >
                  <%= link_to new_customer_session_path,:style =>"color:black;" do %>
                  ログイン
                  <% end %>
                </li>
                <span>&emsp;</span>
                <li class="btn btn-light btn-lg" >
                  <%= link_to new_admin_session_path,:style =>"color:black;" do %>
                  管理ログイン用(後で消す！！！)
                  <% end %>
                </li>
              </div>
            <% end %>
          </ul>
          </div>
        </div>
    </header>
    
    
    <main>
      <% if flash[:notice] %>
        <div class='container'>
          <div class="flash">
            <p class="font-weight-bold pt-5" style="font-size : 20pt" id="notice"><%= notice %></p>
          </div>
        </div>
      <% end %>
      <%= yield %>
    </main>
    
    
    <footer class="shadow-sm">
      <div class='container mt-5'>
        <div class='row'>
          <div class='mx-auto'>
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
    
    
  </body>
</html>